name: CI. Push Build Doker

on:
  release:
    types: [published]
  push:
    tags:
      - "v*.*"
    #branches:
    #  - 'main'

jobs:
  docker:
    env:
        USER_NAME: ${{ github.actor }} #same name in GitHub and DockerHub
        #IMAGE_NAME: ${{ github.repository }}
        IMAGE_NAME: "python.server"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to GitHub Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.USER_NAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.USER_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ env.USER_NAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.USER_NAME }}/${{ env.IMAGE_NAME }}:${{  github.ref_name }}
            ghcr.io/${{ env.USER_NAME }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.USER_NAME }}/${{ env.IMAGE_NAME }}:${{  github.ref_name }}